language: python
python:\
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false

addons:
  apt:
    packages:
    - cython
cache:
  directories:
  - "build"
  - "$HOME/.cache/pip"
install:
  - pip3 install cython
  - python3 setup.py install
before_script:
  - pip3 install codecov
script:
  - coverage run setup.py test
after_success:
  - codecov
